### ISSUE TITLE
UI behaviour at large resolutions

### ISSUE THREAD

**Issue by Yuubari** [erengy/taiga#253] opened 2016-04-14 21:02 UTC
After switching to a new display that uses a native resolution of 2560×1600 I've noticed this weird glitch in Taiga which can be easily reproduced by sending the display into sleep mode or by running exclusive mode applications like MPC-HC with madVR (ignore the black rectangle on the right, that's from the TV's smaller resolution):

![Screenshot](http://i.koumakan.jp/2016-04-14/1460667365.png)

The list-box starts acting as if its height were smaller. Switching tabs does not fix this, however switching to different panes does (as does minimising etc.).

(It's not just Taiga; LINE, the messenger, also exhibits weird behaviour, although limited to the user-drawn frames. Wonder if GDI or whatever is used somehow thinks that 1600 is too much for height and assumes the display is rotated?)

**Comment by erengy** [comment] 2016-05-03 14:04
I looked into this a bit, but couldn't find anyone else experiencing the exact same issue. For relevant display issues, people say updating your graphics driver or using a different cable (e.g. DVI instead of DisplayPort or HDMI) for your monitor connection may work. There's also another suggestion that requires some [registry editing](http://rcaloca.blogspot.com/2014/12/windows-changing-size-position-after.html).

On the other hand, it could be that while going into sleep or waking up, Windows does some resizing or repainting operations that Taiga's not handling appropriately. I don't know how I can reproduce the issue, but if I could, first thing I'd do would be to use [WinSpy++](http://www.catch22.net/software/winspy-17) or a similar application to check the anime list window's actual height.

**Comment by Yuubari** [comment] 2016-05-03 19:12
This behaviour is consistently reproducible on Radeon HD7950 with Catalyst 13.12 and Crimson 16.4, and on Nvidia GTX 590 with the latest GeForce drivers.

I also noticed the same behaviour when World of Warcraft starts in exclusive full-screen mode (that is, not windowed full-screen / borderless window).

I have WinSpy++ installed since I use it all the time for debugging my own stuff; somehow I totally forgot I could do that. Will look into this later.

**Comment by Yuubari** [comment] 2016-05-09 21:17
Just measured the height of the anime list before after this glitch.

Before:

```
Rectangle: (1869,109) - (2552,1535)  -  683x1426
Client Rect: (0,0) - (666,1426)  -  666x1426
```
After:

```
Rectangle: (1869,109) - (3296,846)  -  1427x737
Client Rect: (0,0) - (1410,737)  -  1410x737
```

1427 and 1426 seemed suspicious so I resized the window a bit:

```
Rectangle: (1669,109) - (2552,1464)  -  883x1355
Client Rect: (0,0) - (866,1355)  -  866x1355
```

and forced the display power off state:

```
Rectangle: (1669,109) - (3025,1046)  -  1356x937
Client Rect: (0,0) - (1339,937)  -  1339x937
```

Again, a height of 1355 became a width of 1356. Note that the list itself is definitely not 1356 pixels wide. When this issue triggers, the list is truncated to its original width.

The leftmost panel, with Now Playing, Anime List, etc. buttons is also affected according to WinSpy++. The main window itself is not.

**Comment by Yuubari** [comment] 2016-06-17 06:31
The Windows LINE messenger client, which had a very similar issue with the outer frames of its windows, was just updated with a fix (I reported this issue to them as well) but sadly they did not describe the underlying causes…

**Comment by Yuubari** [comment] 2017-04-26 20:00
Just an update: on a completely fresh reinstall of Windows 10 Enterprise Creators Update, a new display (Dell UP3216q, 4k Ultra HD) and with AMD Crimson 17.4 the behaviour is still the same.

**Comment by erengy** [comment] 2024-10-26 16:52
Sorry for not being able to help with this one.

Closing the issue since v2 is using an entirely different UI framework and this is unlikely to carry over.

**Closed by erengy** 2024-10-26 16:52 UTC
Labels: ui, unknown cause
