### ISSUE TITLE
grid view for anime list

### ISSUE THREAD

**Issue by soredake** [erengy/taiga#1139] opened 2023-06-11 17:17 UTC
Grid view from tachiyomi for example of how this can look:
![Screenshot_20230611-201149_Tachiyomi](https://github.com/erengy/taiga/assets/5204968/8425b79c-7822-4aac-b56c-a75e524dc446)

**Comment by erengy** [comment] 2023-06-11 21:33
Duplicate of #87. This is planned for v2.

**Closed by erengy** 2023-06-11 21:33 UTC
