### ISSUE TITLE
Kitsu 404 causes not to update

### ISSUE THREAD

**Issue by Venipa** [erengy/taiga#902] opened 2020-06-28 10:46 UTC
if an anime does not exist on kitsu it returns a 404 while trying to sync.
once the error shows up you cant sync anymore until you remove the entry from the update/sync queue.

Error if anime does not exist in kitsu
![image](https://user-images.githubusercontent.com/17952364/85945314-4a5d6600-b93d-11ea-8ab4-2d8e2cdc268a.png)

**Comment by erengy** [comment] 2020-10-11 11:13
Duplicate of #706.

**Closed by erengy** 2020-10-11 11:13 UTC
Labels: duplicate
