### ISSUE TITLE
Taiga freezes when Kodi is open

### ISSUE THREAD

**Issue by xKeiro** [erengy/taiga#530] opened 2018-02-24 21:06 UTC
I didn't have this problem until today, but I have Kitsu on automatically refreshing the my anime list on startup, and as of today when it tries to "download anime list" nothing happens and the program gets unresponsive (freezes).

**Comment by erengy** [comment] 2018-02-26 07:39
I tried downloading various people's libraries, including yours, but didn't have any issues.

Are you sure Taiga becomes entirely unresponsive? In my experience, sometimes Kitsu's server takes forever to respond while "Downloading anime list...", but you can actually interact with the application anywhere other than the Anime List page at the time. If that's the case, it's likely a temporary issue with Kitsu or your connection.

Otherwise, try disabling the following options from Settings dialog:

- *Services → Main → Synchronize automatically at startup*
- *Application → General → Startup → Scan library folders for available episodes*

**Comment by wopian** [comment] 2018-02-26 09:14
Taiga itself used to freeze when downloading my list with synopsis'. Doesn't seem to happen these days though (besides not being able to interact with the lists)

Sometimes freezes when scanning 9TB of media though

**Comment by xKeiro** [comment] 2018-02-26 12:15
I'm sure that Taiga became unresponsive, I couldn't click on anything. The problem persisted even yesterday but today when I woke up and checked if it's working now, it worked without an issue. Guess Kitsu had some server issues then?! 

Though it would still be nice if you could cancel the list fetching in case this happens, so you could still use Taiga.

**Comment by erengy** [comment] 2018-03-02 20:08
Taiga shouldn't be freezing while downloading something, because the process takes place in a separate thread. It may freeze briefly right after it's done, though that shouldn't take more than a few seconds.

I set some options in f807570e59540add10386e6ea0487d78dce26146 to be safe.

**Comment by xKeiro** [comment] 2018-03-08 20:05
It's happening now again, only this time it freezes at "Logging in...": 
![2018-03-08_21-02-37_dwm](https://user-images.githubusercontent.com/7066695/37173608-56d55a9e-2314-11e8-9879-702cdeb63ec4.png)

**Comment by xKeiro** [comment] 2018-04-18 21:58
Ok so I think I figured out what really is the cause. It doesn't relate to any of the services, but it relates to Kodi. I had no problem with taiga for days when I deliberately avoided launching Kodi, but when I have both Kodi and Taiga open for some reason Taiga gets unresponsive and even if it gets closed and restarted it's just going to freeze again until you restart your PC. 

What is Kodi?: https://kodi.tv/

**Comment by erengy** [comment] 2018-04-19 14:50
In that case:

- If you have Watchdog or a similar add-on installed, try disabling it or changing its settings (see https://github.com/erengy/taiga/issues/34#issuecomment-63471990).

- If you have *Settings → Services → Control → Allow remote control via HTTP* option enabled, try disabling it (see https://github.com/erengy/taiga/issues/301#issuecomment-271211804).

**Comment by erengy** [comment] 2018-06-07 14:15
Hey @xKeiro, did you try out the things I mentioned above? Should we close this issue?

**Comment by xKeiro** [comment] 2018-06-07 16:04
I just disabled Kodi detection, so it doesn't screw with taiga, feel free to close the issue

**Closed** 2018-06-08 08:00 UTC
Labels: unknown cause

**Comment by RickDB** [comment] 2018-06-22 10:49
Found the root cause is the PlexKodiConnect Kodi addon, whenever that is enabled Taiga will freeze whenever it running certain actions (caching images for instance).
To make sure it was this addon tested the following:

- Start Kodi
- Wait a few minutes and confirm that Taiga is frozen
- Go to addons area and disable the PlexKodiconnect addon
- Will notice that Taiga is no longer frozen

So that addon seems to be conflicting with Taiga, not really an option to keep it disabled as it's pretty integral for syncing the library with Plex with no real alternative so hoping it can be fixed.

Taiga logged nothing so can't attach any logs for that and on the Kodi side nothing related to this as far as I can see, let me know if there's some verbose logging flag that can help pinpoint this.

**Comment by RickDB** [comment] 2018-06-25 12:17
Created a fresh Kodi profile with the PlexKodiConnect addon installed again but this time it no longer locks up Taiga, it must have been some other addons conflicting or that my pretty old profile had some settings in it Taiga didn't like.
