### ISSUE TITLE
HTTP Error #35

### ISSUE THREAD

**Issue by serjflint** [erengy/taiga#691] opened 2018-09-06 13:52 UTC
When I'm trying to download torrents this error appears. Magnet links work fine. 
![image](https://user-images.githubusercontent.com/4900246/45161763-04825b80-b206-11e8-8b13-977fb2f5178f.png)

**Comment by serjflint** [comment] 2018-09-06 13:56
The same happens when I'm tryng to search torrent on nyaa.si from 'Anime List' tab.

**Comment by erengy** [comment] 2018-09-06 14:11
It's likely a temporary issue with your connection. If it doesn't resolve by itself, you can try to following:

1. Go to _Settings_ → _Advanced_ and set _Application / Disable certificate revocation checks_ to `true`.
2. Restart Taiga.

Closing this issue because it's a duplicate of #312.

**Closed by erengy** 2018-09-06 14:11 UTC

**Comment by serjflint** [comment] 2018-09-06 14:38
Helps with torrents but the search function still doesn't work

**Comment by serjflint** [comment] 2018-09-06 14:46
I found the cause of the issue. My provider blocked access to nyaa.si.
