### ISSUE TITLE
Selecting "I am watching this anime" when Taiga is unable to find out on its own

### ISSUE THREAD

**Issue by SonicBlader** [erengy/taiga#447] opened 2017-08-10 12:48 UTC
Hello! I have been using Taiga for a while & it has really made my anime life amazing! Thank you!

The one thing that bothered me slightly was that when Taiga cannot find out which Anime I am watching, I am given a list of probable animes from which I can select which one I am watching. But more than half of the times, the actual anime I am watching won't be on the list. In such cases, Taiga suggests me to search for the anime. Even if I find the anime I am watching in the search, I cannot select it as the currently watch anime. I will have to manually add the name of the Anime to the Local tags for it to find the episodes. Sometimes it doesn't work even if I enter the entire episode name.

Please take a look at this Imgur Album for a pictorial representation of what I mean - [Imgur](http://imgur.com/a/YNOhI)

I am at a loss of what to do to make Taiga recognize the episodes. I think it would be nice to have an option to select which anime I am currently watching from the lists. Something like Right-click on the correct anime, select "I am watching this". 

Thank you! :)

**Comment by erengy** [comment] 2017-09-03 15:49
Hi there @SonicBlader, and sorry for the late reply.

In general, "How does anime recognition work?" section at the [FAQ page](http://taiga.moe/#support) should give you some clues about the recognition process.

> Even if I find the anime I am watching in the search, I cannot select it as the currently watch anime.

If the anime in question is not in your list, you must first add it to your list. You can do this by right-clicking on an item at Search page.

If it's already in your list, you can select it from the list displayed at Now Playing page. This is equivalent to manually adding an alternative title from Anime Information dialog.

> Sometimes it doesn't work even if I enter the entire episode name.

Assuming that the filename is `[TaigaSubs]_Anime_Title_-_01_[BD_1080p].mkv`, the alternative title here is `Anime Title`. Adding the entire filename as an alternative title will have no effect.

> Please take a look at this Imgur Album for a pictorial representation of what I mean

`Durarara!! Episode 12.5` is really a special case here. Taiga is unable to handle ".5" episodes properly (previously at #90), especially when the redirected anime has multiple episodes (as in *Durarara!! Specials*). In most other cases, the issue is resolved by adding an alternative title.

**Closed** 2017-10-11 08:15 UTC
