### ISSUE TITLE
Torrents no longer open automatically for Deluge

### ISSUE THREAD

**Issue by 190nm** [erengy/taiga#229] opened 2016-02-07 23:29 UTC
http://i.imgur.com/otVddX3.gifv

I use deluge and seemingly after this latest update, taiga no longer opens torrent files automatically.

**Comment by erengy** [comment] 2016-02-12 17:21
Related to #86 and ff9090a8eb84a919b3eb873138df1ed6aaddf45a.

As of v1.2.3, "Use anime folders as the download folder" option works for Deluge too, but there's some setup involved: First, from Deluge's *Preferences → Interface*, disable *Classic Mode*. Then, start a local deamon from *Connection Manager* and connect to it. This will allow Taiga to automatically set the download folder.

If this isn't what you want, you may just disable the "Use anime folders as the download folder" option from Taiga's *Settings → Torrents → Downloads*.

I should probably modify [these lines](https://github.com/erengy/taiga/blob/82f0664dd7595364113f7d823ba7a0d0c03d505a/src/track/feed_aggregator.cpp#L346-L350) so that it doesn't confuse other people in the future.

**Comment by VivaLaPanda** [comment] 2016-02-15 06:37
This doesn't work for me either. I'm running deluge in daemon mode, but the files taiga downloads don't get added to Deluge. I tried pointing it towards the command line exe and the default. Command line just opens a prompt for half a second, which might be an error. Everything works fine if I turn off the "Use anime folders as the download folder", but I would like to use the feature.

**Comment by kasokz** [comment] 2016-05-15 20:52
I'm not sure what's causing my problem, but this feature seems to not work on all of my downloads. For example, when I download a Dragon Ball Super torrent Taiga manages to start the download over deluge-console and it creates the appropriate folder for the file. But on most other shows, it doesn't even show in my deluge UI. The log doesn't tell me anything about this behaviour.

**Comment by himie** [comment] 2016-05-17 17:05
After a long time of this not working for me either with deluge I decided to look into it.
I did change everything to how it's suggested. Disabled classic mode, using daemon, and deluge-console on taiga but it still didn't work.

If you look at the [command](http://i.imgur.com/zCcR2ZK.png) Taiga starts deluge-console with it's pretty obvious:
`"C:\Program Files (x86)\Deluge\deluge-console.exe" add -p \"E:\Anime\Pan de Peace!\\" \"C:\Users\himie\AppData\Roaming\Taiga\data\feed\d3d3Lm55YWEuc2U=\[Kaitou]_Pan_de_Peace!_-_07_[720p][10bit][76CE7590].mkv.torrent\"`

The problem is the double \\ at the end of the anime folder where it's saved to. Deluge can't parse this and [errors out](http://i.imgur.com/2ydRD0S.png) saying there's no closing quotation.

This happens because Taiga saves anime folder paths with a trailing \ like `E:\Anime\Pan de Peace!\` so when this is escaped it ends up with \\"

[Simple solution](http://i.imgur.com/3CTM4Iw.jpg): change anime folders saved path without a trailing \

A bit of a pain to change every anime path manually but at least it makes it work.

**Comment by erengy** [comment] 2016-05-17 17:48
Could you try out [this build](http://taiga.moe/latest.html) and see if it fixes the issue?

**Comment by himie** [comment] 2016-05-17 18:01
Yes, that build fixes it. Thanks!

**Closed** 2016-08-05 18:55 UTC
Labels: torrent
