### ISSUE TITLE
Prompt updating list based on % watched or time remaining

### ISSUE THREAD

**Issue by AzureBlaze** [erengy/taiga#164] opened 2015-08-16 23:03 UTC
Currently in Taiga I can set it so that will prompt to update the episode after a certain amount of time has passed, this is pretty useful, but sometimes I may pause the show or the episodes might be longer than usual. In cases like this it would be nice if the program had an option prompting me to update after say 95% of the episode was done or there was 1:50 left.

**Comment by erengy** [comment] 2015-08-17 07:00
While we're at it, we should implement eye tracking to make sure the user is *really* watching it. :eyes:

Joking aside, yes, that'd be ideal. However, we'd need two pieces of information to make it work:

1. Media length (e.g. 23:43)
2. Media state (e.g. playing, paused, stopped)

The problem is, there's just no way to get these information in all cases. Not all media players have an API that expose their internal state to external processes. Even the ones that do, may have some limitation such as the requirement to be executed with some special command (e.g. `mpc-hc.exe /slave`). Obviously, it doesn't work for web browsers at all... In other words, this feature would occasionally not work, which I'm afraid would be more confusing than helpful.

**Comment by ConnorKrammer** [comment] 2015-08-17 07:56
I've been thinking about this for a while as well, and it's definitely problematic. Media length could be, in theory, provided by MAL (not sure if Hummingbird supplies this information), but I have a suspicion the API doesn't support this type of query at the moment. Media state, however, is harder.

One method would be to do the following:

1. Is the player in focus?
2. If so, monitor the area controlled by the player.
3. If the area of the screen owned by the player is being updated in an area larger than [insert reasonable default here], set status to "playing".
4. Otherwise, set it to "not playing".
5. While status is set to "playing", increment a timer.
6. Set media length as one of the following:
  1. Length returned by API request to anime service
  2. Smart default based on media type. For example:
    - TV: 25 min
    - OVA: 25 min
    - Special: 5 min
    - Movie: 60 min
    - And so on. It would be a good idea to make a statistical sample to determine appropriate defaults.
6. When the "playing" timer hits x% of the media's length, set the episode as watched according to the user's settings.

This would require some method of tracking what's going on in the screen. Mouse movement, normally a good indicator of user presence, isn't really helpful here because most users don't use their mouse while watching anime. In comparison, while monitoring the screen isn't the most elegant solution, it *is* fairly robust. The screen wouldn't have to be polled very often (anime has a low frame rate to start with), but there could be problems when the player is inside a browser; I'm not really sure how Taiga is detecting these players in the first place.

Regardless of detection methods, the length of time before the episode is marked as watched could still be improved in the way I describe above.

(end wall of text)

**Comment by vendethiel** [comment] 2015-08-17 09:53
I'd rather taiga not intrude that much... :)

**Comment by erengy** [comment] 2016-01-13 02:24
Closing this issue, because currently there's no viable solution to track media length and state.

**Closed by erengy** 2016-01-13 02:24 UTC
Labels: feature request
