### ISSUE TITLE
Mac OS Support

### ISSUE THREAD

**Issue by george-emerald** [erengy/taiga#1048] opened 2022-01-26 15:14 UTC
Are there any plans for Mac OS support? Hachidori is the closest thing and it's nowhere near as good as taiga. It's practically the only thing I miss from Windows. I saw an issue on it saying it's planned for v2.0. Has any progress been made on 2.0? Is there a deadline? It's been seven years since the issue I found. There's bound to be some progress.

**Comment by wopian** [comment] 2022-01-26 16:09
Duplicate of https://github.com/erengy/taiga/issues/92

**Comment by george-emerald** [comment] 2022-01-27 05:01
Yes. That issue was back in 2015, i.e. seven years ago. Any progress? It's been seven years.

**Comment by moyitpro** [comment] 2022-02-01 11:23
> Are there any plans for Mac OS support? Hachidori is the closest thing and it's nowhere near as good as taiga. It's practically the only thing I miss from Windows. I saw an issue on it saying it's planned for v2.0. Has any progress been made on 2.0? Is there a deadline? It's been seven years since the issue I found. There's bound to be some progress.

I'm the developer of Hachidori and Hachidori only covers the functionality to update your lists automatically based on what you are watching. Shukofukurou focuses on list management of both Anime and Manga. Taiga can only manage Anime lists and doesn't have custom list support on AniList. Shukofukurou has more features than Taiga when it comes to list management. They are separate apps since Hachidori can't be on the App Store as sandboxing limits some of the features needed in the app.

Of course, some of the extra features require a donation to help cover the Apple Developer Program, which is needed for the code signing certificates, the ability to distribute the apps on the App Store, and time spent developing the app since it's mainly myself developing the app, which is done on my free time.

**Closed** 2022-02-01 17:57 UTC
