### ISSUE TITLE
Main window hangs when Library Scans access slow or unavailable direct-ip/UNC paths

### ISSUE THREAD

**Issue by BinToss** [erengy/taiga#1038] opened 2021-10-13 04:34 UTC
# Workaround
To avoid freezing the main window frequently, uncheck the setting `Settings > Library > Real-time monitor > Detect new file and folders under library folders`. Doing so will cause Library scans to be initiated manually or when an episode needs to be played/found.

# Solution
- [ ] Perform library scans on new threads. One thread per library location.
  - Results would be combined by adding only the 'episode found' results to a new collection (Array, List, et cetera) i.e. `if (episodeFile.isFound){ EpisodesList.Add(episodeFile) }`.

**Comment by FreezyLemon** [comment] 2021-10-13 15:39
This looks like a duplicate of #371.

> One thread per library location

I think one thread per storage device makes more sense (provided there's a library on the device of course)

**Closed as completed** 2021-10-14 04:49 UTC
