### ISSUE TITLE
Clicking on notifications does not bring Taiga to front

### ISSUE THREAD

**Issue by asakurato** [erengy/taiga#528] opened 2018-02-03 18:34 UTC
When new episodes are uploaded, I get notifications about it. When I click it, no matter where I am, only Taiga icon on taskbar flashes, not opening the app itself. I think that's not supposed to happen and app should open when you click on notifications (or maybe it's designed like this?). I know there is option to download immediately, but that's not an option for me unfortunately. I'm on Windows 10 Fall creators update.

**Comment by asakurato** [comment] 2018-02-03 18:54
Oh, I forgot to say, but it's not only from episode downloads, but also when you play any episode and click the notification. Same happens.

**Comment by erengy** [comment] 2018-02-14 21:50
Taiga uses [`SetForegroundWindow`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633539(v=vs.85).aspx) function to bring its window into the foreground. This doesn't always work, because, quoting from MSDN:

> The system restricts which processes can set the foreground window. (...) An application cannot force a window to the foreground while the user is working with another window. Instead, Windows flashes the taskbar button of the window to notify the user.

In other words, Taiga does try bringing itself to front, but Windows does not allow it. This is by design of the operating system. It's not an issue that can be resolved without relying on hacks, which may cause other troubles.

**Comment by asakurato** [comment] 2018-02-14 21:52
Oh, didn't know it was designed to be like that. Guess I'll continue using Taiga as I do now.

**Closed** 2018-02-14 21:52 UTC
Labels: cannot fix, ui

**Comment by erengy** [comment] 2018-02-15 12:12
For future reference, I tried various workarounds before calling `SetForegroundWindow`, but none of them seemed to work on Windows 10 Fall Creators Update:

- Sending `VK_MENU` with `keybd_event` or `SendInput`
- Setting `VK_F22` as hotkey and sending it as input
- Calling `ShowWindow` with `SW_MINIMIZE`
- Calling `SetWindowPos` with `HWND_TOPMOST`
- Calling `SwitchToThisWindow` with `TRUE` to simulate <kbd>Alt</kbd>+<kbd>Tab</kbd>

I haven't tried the following, because they're making system-wide changes:

- Calling `AllowSetForegroundWindow` with `ASFW_ANY`
- Calling `SystemParametersInfo` with `SPI_SETFOREGROUNDLOCKTIMEOUT`

I should also add that `SetForegroundWindow` works as expected on Windows 8.1, without any workarounds.

**Comment by Yuubari** [comment] 2019-11-20 09:09
I experienced a similar issue when working on KanColleViewer so I was wondering if perchance Taiga uses multiple threads and attempts to invoke `SetForegroundWindow`  from outside of the main UI thread (this applies to controls in general, not just toasts that belong to the main thread). That is what always failed in KCV and was solved by adding a check like this: Yuubari/KanColleViewer@cf072443caeb03f4e00f50679eb2e5cbd622da45. That's WPF, however. For Windows Forms there is the `InvokeRequired` property and the `Invoke` method, used in a similar way:

```c#
private void action()
{
    if (mainWindow.InvokeRequired)
    {
        mainWindow.BeginInvoke(new Action(action));
        return;
    }
    DoSomeToasting();
}
```
