### ISSUE TITLE
add support shikimori.one

### ISSUE THREAD

**Issue by LevganSaxen** [erengy/taiga#1064] opened 2022-06-10 22:36 UTC
https://shikimori.one/api/doc

**Comment by kiriya-aoi** [comment] 2022-06-10 22:59
Duplicate of https://github.com/erengy/taiga/issues/381

**Comment by oplexz** [comment] 2022-06-11 09:52
@LevganSaxen since this issue is a duplicate, you should probably close it.

**Closed** 2022-06-11 12:36 UTC
Labels: duplicate
