### ISSUE TITLE
[Suggestion] Give an option to disable notification messages

### ISSUE THREAD

**Issue by ruudschouten** [erengy/taiga#193] opened 2015-12-11 15:53 UTC
I've added a few anime on my Plan to Watch list, some of which are not yet approved, and every 5 minutes or so there's a popup saying that the Update Failed because the anime hasn't been approved yet.
This is pretty annoying and I would really like to see a option to disable the notifications.

**Comment by erengy** [comment] 2015-12-11 16:30
Duplicate of #138.

You could get rid of the error by disabling auto synchronization (from Tools menu), but that's just a symptom of a larger problem.

1. MAL returns unapproved anime in API search results.
2. MAL doesn't allow people to add unapproved anime to their list.
3. MAL doesn't tell you whether an anime is approved or not, until you try adding it to your list.
4. Some anime stay unapproved for months, due to the lack of anime moderators.

Ideally, MAL would resolve at least one of these issues. For now, you need to manually remove the unapproved entries from your update queue (from History page), otherwise Taiga won't be able to process the remainder of the queue and synchronize your list.

**Closed by erengy** 2015-12-11 16:30 UTC
Labels: duplicate
