### ISSUE TITLE
Taiga failing to add Kitsu account on latest release.

### ISSUE THREAD

**Issue by Renari** [erengy/taiga#431] opened 2017-06-11 18:47 UTC
I've tried to reproduce this on the develop branch however everything seems to work there. The issue happens when attempting to add a new Kitsu account and syncing for the first time. The status bar reads `Reading account information... (164 bytes)` and shortly after crashes.

My Taiga log file reads the following:
```
2017-06-11 08:45:34 [Warning] settings.cpp:65 taiga::AppSettings::HandleCompatibility | Upgraded from v1.2.5 to v1.3.0-alpha
2017-06-11 08:46:01 [Warning] anime_db.cpp:440 anime::Database::LoadList | Reading list in compatibility mode
2017-06-11 08:46:01 [Error] file_search.cpp:56 FileSearchHelper::Search | >>
The system cannot find the path specified.

Path: \\?\C:\Users\Arimil\AppData\Roaming\Taiga\data\db\image\*
2017-06-11 08:46:01 [Error] file_search.cpp:56 FileSearchHelper::Search | >>
The system cannot find the path specified.

Path: \\?\C:\Users\Arimil\AppData\Roaming\Taiga\data\db\image\*
2017-06-11 08:46:53 [Warning] anime_db.cpp:72 anime::Database::HandleCompatibility | Clearing image URLs
2017-06-11 08:46:53 [Warning] anime_db.cpp:440 anime::Database::LoadList | Reading list in compatibility mode
2017-06-11 08:48:15 [Warning] anime_db.cpp:72 anime::Database::HandleCompatibility | Clearing image URLs
2017-06-11 08:48:15 [Warning] anime_db.cpp:440 anime::Database::LoadList | Reading list in compatibility mode
2017-06-11 14:40:35 [Warning] anime_db.cpp:72 anime::Database::HandleCompatibility | Clearing image URLs
2017-06-11 14:40:35 [Warning] anime_db.cpp:440 anime::Database::LoadList | Reading list in compatibility mode
2017-06-11 14:41:12 [Warning] anime_db.cpp:72 anime::Database::HandleCompatibility | Clearing image URLs
2017-06-11 14:41:12 [Warning] anime_db.cpp:440 anime::Database::LoadList | Reading list in compatibility mode
2017-06-11 14:41:33 [Warning] anime_db.cpp:72 anime::Database::HandleCompatibility | Clearing image URLs
2017-06-11 14:41:33 [Warning] anime_db.cpp:440 anime::Database::LoadList | Reading list in compatibility mode
2017-06-11 14:42:58 [Warning] anime_db.cpp:72 anime::Database::HandleCompatibility | Clearing image URLs
2017-06-11 14:42:58 [Warning] anime_db.cpp:440 anime::Database::LoadList | Reading list in compatibility mode
2017-06-11 14:43:53 [Warning] anime_db.cpp:72 anime::Database::HandleCompatibility | Clearing image URLs
2017-06-11 14:43:53 [Warning] anime_db.cpp:440 anime::Database::LoadList | Reading list in compatibility mode
2017-06-11 14:44:14 [Warning] anime_db.cpp:72 anime::Database::HandleCompatibility | Clearing image URLs
2017-06-11 14:44:14 [Warning] anime_db.cpp:440 anime::Database::LoadList | Reading list in compatibility mode
```
Creating the images directory doesn't seem to help and I get the same log.

**Comment by Renari** [comment] 2017-06-11 19:04
Upon looking into this a bit more, I am not unable to reproduce the issue. I build the develop branch for release and tried using that build and got the same issue. I then tried removing my data directory and using the one that was generated in my debug build that was working. This caused the issue to disappear on latest and develop builds.

**Comment by erengy** [comment] 2017-07-18 14:41
It seems to be an edge case as I couldn't reproduce the issue and no one else reported it so far.

Do you still have a copy of the data directory that caused the crash? If you do, you may either send it to me (after removing any sensitive information) or try debugging it yourself with Visual Studio.

**Comment by Renari** [comment] 2017-07-18 14:43
Unfortunately I do not or I would have done that already.

**Comment by erengy** [comment] 2017-07-18 18:36
Ah, that's a shame. It seems to be crashing while trying to parse Kitsu's response to a user authentication request. But I can't think of a reason other than you were using an older build of Taiga or that there was a temporary problem with Kitsu's server at the time.

I'm closing this issue now, but I'll revisit your report if a similar issue occurs.

**Closed by erengy** 2017-07-18 18:36 UTC

**Comment by Renari** [comment] 2022-04-15 18:35
After an extremely long time long time it seems this is happening again and I've been unable to resolve it, the 1.3.1 release gives the above authentication error and it seems the develop branch builds the same 1.3.1 release. I've tried the beta release as well and in that release syncing seems to silently fail.
