### ISSUE TITLE
HTTP error 404 while using VPN

### ISSUE THREAD

**Issue by trybefore** [erengy/taiga#844] opened 2020-01-06 10:41 UTC
https://i.imgur.com/Cm1hAbq.png

I get this error whenever I try to download torrent files through taiga while using PIA VPN.

works fine while disconnected from VPN

**Comment by erengy** [comment] 2020-01-07 18:50
Please [run Taiga in debug mode](https://github.com/erengy/taiga/wiki/How-to-run-Taiga-in-debug-mode) and reproduce the issue. Then either send the log file to me via the email address in my profile, or post it here after making sure it doesn't include any sensitive information.

**Comment by erengy** [comment] 2020-01-08 20:35
Got it, thanks. This looks like the same issue @inexplicabro reported a few months ago at Discord. It's not actually related to your VPN. You probably downloaded a different file while being disconnected, then assumed it was due to your connection.

The download link for the [torrent](https://www.tokyotosho.info/details.php?id=1407929) in question is invalid:

    https://torrent.erai-ddl3.info/Torrent/2019/Fall/BNHA4/%5BErai-raws%5D Boku no Hero Academia 4th Season - 12 %5B1080p%5D%5BMultiple Subtitle%5D.mkv.torrent

A URL cannot contain spaces. It must have been properly encoded as:

    https://torrent.erai-ddl3.info/Torrent/2019/Fall/BNHA4/%5BErai-raws%5D%20Boku%20no%20Hero%20Academia%204th%20Season%20-%2012%20%5B1080p%5D%5BMultiple%20Subtitle%5D.mkv.torrent

Taiga uses the "URL" as is, so the server rightfully rejects the request with a `400 Bad Request` response. Note that web browsers don't have this issue, probably because they parse and re-encode links to be safe.

AFAIK this only happens with Erai-raws releases at TokyoTosho. Might have something to do with their submission API. /cc @Edward-K

**Comment by Edward-K** [comment] 2020-01-09 01:12
Hi,

I've updated the site to encode the URL paths in HTML href. Can you try now?

**Comment by erengy** [comment] 2020-01-09 12:14
Hey @Edward-K, thanks for your response.

I can confirm that the torrent links at the website seem to be properly encoded now. But the issue persists in `<link>` elements of the RSS feed.

**Comment by Edward-K** [comment] 2020-01-09 13:11
RSS now fixed, thanks for the feedback.

**Comment by erengy** [comment] 2020-01-09 13:46
Now the problem is that some links are encoded twice and therefore do not work.

[Here](https://www.tokyotosho.info/details.php?id=1408403), for instance, `%5B` is erroneously encoded as `%255B`, so the download link returns "The requested URL was not found on this server":

```diff
-http://tracker.minglong.org/torrents/%5BKiteSeekers-Licca%5D%20Idol%20Densetsu%20Eriko%20-%2049%20%5BBD%20XviD%20MP3%20640x480%5D%20%5B1E91DCAE%5D.avi.torrent
+http://tracker.minglong.org/torrents/%255BKiteSeekers-Licca%255D%2520Idol%2520Densetsu%2520Eriko%2520-%252049%2520%255BBD%2520XviD%2520MP3%2520640x480%255D%2520%255B1E91DCAE%255D.avi.torrent
```

**Comment by Edward-K** [comment] 2020-01-10 01:14
Hi,
3rd time's the charm? Should be fixed now.

**Comment by erengy** [comment] 2020-01-10 10:32
Everything seems to be in order now, thanks!

@trybefore Could you try it on your end too?

**Closed** 2020-01-22 17:27 UTC
