### ISSUE TITLE
darkmode/theme

### ISSUE THREAD

**Issue by Smeagol001** [erengy/taiga#1129] opened 2023-04-24 20:57 UTC
it would be really nice to have said option since nowadays ypou run stuff in datrrkmode anyways since its easier on the eyes
and everytime you open taiga you get flashbanged cxause its damn white

**Comment by kiriya-aoi** [comment] 2023-04-24 21:23
duplicate of https://github.com/erengy/taiga/issues/807

**Closed** 2023-05-29 14:16 UTC
