### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by Mightyyt** [erengy/taiga#981] opened 2021-03-01 16:11 UTC
Support multi RSS feeds with with custom name, like for example: 

- Airing Animes: nyaa.si/***
- Movies: nyaa.si/**
- Anime's seasons: nyaa.si/****

**Comment by Mightyyt** [comment] 2021-03-01 16:18
The reason is that I use different fansubs groups for different type of animes like movies and complete seasons

**Comment by erengy** [comment] 2021-03-02 02:23
Duplicate of #40.

**Closed by erengy** 2021-03-02 02:23 UTC
Labels: duplicate
