### ISSUE TITLE
[Bug] Parsing wrong seasons of anime

### ISSUE THREAD

**Issue by jasonmbrown** [erengy/taiga#963] opened 2021-01-20 21:02 UTC
It doesn't happen very often however there are a few shows that have Seasons broken into Parts. (EG Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season) 

Taiga keeps identifying Part 2 of Season 2 as Part 1. Im not sure how to fix this. Or if its a bug.

The File name in question is [Erai-raws] Re.Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2 - 01 [1080p][Multiple Subtitle].mkv

I will manually have to increment the episodes since it cant parse. If there's a way to force the now playing without effecting the other season let me know.

**Comment by erengy** [comment] 2021-01-20 22:32
Duplicate of #960.

**Closed by erengy** 2021-01-20 22:32 UTC
