### ISSUE TITLE
Custom List (Anilist) 

### ISSUE THREAD

**Issue by ChristopheRoyer21** [erengy/taiga#927] opened 2020-09-07 01:43 UTC
Hello,
I know it has been addressed in an issue two years ago, but is there any plans on implementing custom list from Anlist on the app? I know at that time it wasn't planned to add feature for specific service, but maybe it has changed two years after.
Thank you for your work!

**Comment by wopian** [comment] 2020-09-07 01:53
Duplicate of https://github.com/erengy/taiga/issues/590

**Closed** 2020-10-10 14:10 UTC
Labels: duplicate
