### ISSUE TITLE
MAL unapproved anime cannot be removed from the local list

### ISSUE THREAD

**Issue by Creqaw** [erengy/taiga#212] opened 2016-01-12 18:39 UTC
I added this anime: http://myanimelist.net/anime/32376/Kindaichi_Shounen_no_Jikenbo_Returns:_Akechi_Keibu_no_Jikenbo as "Plan to watch" through the Taiga search function. I got an unapproved message but ignored it. 
I moved it to watching while watching and now it's stuck in the local list. It's not on my watching list on MAL but it's in the list in Taiga and it throws "update failed, anime unapproved" messages every few seconds. I cannot remove it either as it gives the same error.

**Comment by erengy** [comment] 2016-01-13 02:59
Duplicate of #138.

> You can simply go to History and remove it from the queue.



> you need to manually remove the unapproved entries from your update queue (from History page), otherwise Taiga won't be able to process the remainder of the queue and synchronize your list.

**Closed by erengy** 2016-01-13 02:59 UTC
Labels: duplicate, myanimelist
