### ISSUE TITLE
Not responding and computer lag

### ISSUE THREAD

**Issue by monolithsan** [erengy/taiga#176] opened 2015-09-11 03:08 UTC
Recently I have started watching one piece and using mal to keep track of the episodes but after a few hours my entire computer will get extremely choppy(just moving my mouse to a button is difficult it lags so badly) until I close taiga(and taiga is listed as not responding and very high cpu usage)

**Comment by erengy** [comment] 2015-09-13 04:29
This seems to be the same [issue](https://forums.hummingbird.me/t/windows-taiga/10565/397) that I received last month:

> Started in this latest update, when i open an episode and leave it minimized to go do something else, some time later about 10 minutes the entire PC becomes really slow, including the mouse itself, and i need to very slowly open task manager and kill Taiga.

Unfortunately, I haven't been able to figure out the cause so far. Could you do the following things for me?

1. Download and run [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx) (it's basically a more advanced Task Manager).
2. Double-click on *Taiga.exe*.
3. Take screenshots of *Performance* and *Performance Graph* tabs when Taiga acts up again.

**Comment by monolithsan** [comment] 2015-09-24 17:47
Sorry for the late response I have been kind of busy but I got around to watching more and after a few hours it once again did the same thing.  it took like 10 minutes to take the screenshots it was so laggy <.< but as soon as I closed taiga it went away again
![2015-09-24_13-39-58](https://cloud.githubusercontent.com/assets/14228451/10081391/b56f62ee-62c2-11e5-9bac-119789eb2ee5.png)
![2015-09-24_13-41-48](https://cloud.githubusercontent.com/assets/14228451/10081392/b78dc05c-62c2-11e5-95e6-93672473f884.png)

**Comment by monolithsan** [comment] 2015-09-24 17:49
oh I almost forgot that this time I noticed my computer gradually getting slower but it would tend to not last only 30 seconds or so but eventually it just tips over and becomes unusable and taiga needs to be closed

**Comment by radgeRayden** [comment] 2016-03-14 02:52
Still happening here. Windows 10, mpv. Taiga becomes unresponsive and the whole system freezes until I kill taiga.

**Comment by erengy** [comment] 2018-01-06 15:37
Could you try upgrading to [v1.3.0-beta](https://github.com/erengy/taiga/releases/tag/v1.3.0-beta), if you haven't done so already? I've recently made some changes that might have fixed this.

**Comment by monolithsan** [comment] 2018-01-10 19:22
I will make sure to update to this beta release, I doubt I will be able to give you any feedback on if the changes have worked or not though.  I finished watching the longer series that were making it lock up when chain viewed and have not been having any issues since those were completed.

**Comment by erengy** [comment] 2018-04-30 10:31
I'm closing this issue on the assumption that it was resolved in v1.3, but let me know if it persists.

**Closed by erengy** 2018-04-30 10:31 UTC
Labels: unknown cause
