### ISSUE TITLE
beta.crunchyroll.com Doesn't Work

### ISSUE THREAD

**Issue by RyutoSetsujin** [erengy/taiga#1078] opened 2022-09-05 22:31 UTC
I've been watching all my anime through Crunchyroll. I tried using Taiga today, and when I tried to watch a show, Taiga wasn't recognizing it...? I enabled the option for Taiga to recognize Crunchyroll, so I'm sure this is just a issue with the beta site.

**Comment by erengy** [comment] 2022-10-03 14:36
Duplicate of #994.

**Closed by erengy** 2022-10-03 14:36 UTC
