### ISSUE TITLE
Update failed: 501 Not Implemented (Apache server)

### ISSUE THREAD

**Issue by ernest88** [erengy/taiga#161] opened 2015-08-11 20:10 UTC
![upload error](https://cloud.githubusercontent.com/assets/8308647/9209207/99e3cea8-4075-11e5-8530-f6c34399419b.jpg)

**Comment by erengy** [comment] 2015-08-11 20:35
Duplicate of #157.

This issue is fixed in v1.2.2. You can update the application via *Help → Check for updates*.

**Closed by erengy** 2015-08-11 20:35 UTC
Labels: duplicate
